CREATE TABLE [dbo].[Books] (
    [BookId]                              INT            IDENTITY (1, 1) NOT NULL,
    [name]                                NVARCHAR (MAX) NULL,
    [author]                              NVARCHAR (MAX) NULL,
    [Отчество]                            NVARCHAR (MAX) NULL,
    [description]                         NVARCHAR (MAX) NULL,
    [Дата_рождения]                       NVARCHAR (MAX) NULL,
    [Год_поступления]                     NVARCHAR (MAX) NULL,
    [Год_окончания]                       NVARCHAR (MAX) NULL,
    [Образование]                         NVARCHAR (MAX) NULL,
    [Год_окончания_школы]                 NVARCHAR (MAX) NULL,
    [Номер_школы]                         NVARCHAR (MAX) NULL,
    [genre]                               NVARCHAR (MAX) NULL,
    [year]                                NVARCHAR (MAX) NULL,
    [picture]                             NVARCHAR (MAX) NULL,
    [Номер_телефона_родителей]            NVARCHAR (MAX) NULL,
    [url]                                 NVARCHAR (MAX) NULL,
    [dimensions]                          NVARCHAR (MAX) NULL,
    [weight]                              NVARCHAR (MAX) NULL,
    [Гражданство]                         NVARCHAR (MAX) NULL,
    [Документ_подтверждающий_гражданство] NVARCHAR (MAX) NULL,
    [Многодетная_семья]                   NVARCHAR (MAX) NULL,
    [barcode]                             NVARCHAR (MAX) NULL,
    [Срок_действия]                       NVARCHAR (MAX) NULL,
    [Основание_поощрение]                 NVARCHAR (MAX) NULL,
    [Основание_взыскания]                 NVARCHAR (MAX) NULL,
    [media]                               NVARCHAR (MAX) NULL,
    [От_какого_числа]                     NVARCHAR (MAX) NULL,
    [Внутриние_перемещения]               NVARCHAR (MAX) NULL,
    [Характеристика_выпускника]           NVARCHAR (MAX) NULL,
    [Трудоустройство_выпускника]          NVARCHAR (MAX) NULL,
    [Продвижение_выпускника]              NVARCHAR (MAX) NULL,
    [price]                              nvarchar   NULL,
    PRIMARY KEY CLUSTERED ([BookId] ASC)
);

